### ISSUE TITLE
Ubuntu CIS profile 1604 error?

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubblestack_data#32]
_From @redonkuless on July 13, 2017 20:42_

Line: 629 I believe should read, 

 - net.ipv4.icmp_echo_ignore_bogus_error_responses:

instead of:

- icmp_echo_ignore_bogus_error_responses:

_Copied from original issue: hubblestack/hubble#64_

**Comment by basepi** [comment]
Thanks for the report, @redonkuless! Any chance you could submit a PR fixing this? Otherwise we'll grab it when we get a chance.

**Comment by redonkuless** [comment]
No idea how to do that. New to this.


________________________________

**Comment by basepi** [comment]
No worries, I'll get this fixed a little later today.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble#67
